### ISSUE TITLE
Wrong project folder SW4STM32

### ISSUE THREAD

**Issue by elgarbe** [duro80/Makefile4CubeMX#2]
You are looking the project in a folder called SW4STM32 but CubeMX doesn't make that folder, I have the .cproject under this folder:
E:\UWB\WS_F030CC\UWB_Board01_init_code
and get an error:
Traceback (most recent call last):
  File "E:\ARM\Makefile4CubeMX-master\CubeMX2Makefile.py", line 183, in <module>
    for name0 in os.listdir(os.path.join(proj_folder,"SW4STM32")):
WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 'E:\\UWB\\WS_F030CC\\UWB_Board01_init_code\\SW4STM32/*.*'

**Comment by duro80** [comment]
Hello.
I updated readme.md file for details about settings of STM32CubeMX

Try this:
Before using the script CubeMX2Makefile.py make sure the software STM32CubeMX are set these preferences:
In Project/Settings:
 - Toolchain IDE: SW4STM32
 - Generate under root is unchecked

**Comment by elgarbe** [comment]
Ok, I erase the project, config CubeMX as you stated and now I get this error:

```
E:\UWB\WS_F030CC\UWB_Board01_init_code\SW4STM32\UWB_Board01_init_code\.project
True True
TARGET:                 UWB_Board01_init_code
Traceback (most recent call last):
  File "E:\ARM\Makefile4CubeMX-master\CubeMX2Makefile.py", line 233, in <module>
    nodes = rootProject.findall('linkedResources/link[type=\'1\']/location')
  File "C:\Python26\lib\xml\etree\ElementTree.py", line 355, in findall
    return ElementPath.findall(self, path)
  File "C:\Python26\lib\xml\etree\ElementPath.py", line 198, in findall
    return _compile(path).findall(element)
  File "C:\Python26\lib\xml\etree\ElementPath.py", line 176, in _compile
    p = Path(path)
  File "C:\Python26\lib\xml\etree\ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)
```

**Comment by duro80** [comment]
It may be due using python 2.6 (http://stackoverflow.com/questions/35662542/extracting-specific-xml-tag-value-using-python)
I tested only with python 2.7
